const data = {
  products: [
    {
      name: 'Shirt',
      slug: 'Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'Fit Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      brand: 'Adidas',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Shirt',
      slug: 'Shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pant',
      slug: 'Pant',
      category: 'Shirts',
      image: '/images/Pant1.jpg',
      brand: 'Nike',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Shirt',
      slug: 'Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Shirt',
      slug: 'Shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      price: 70,

      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Pant',
      slug: 'Pant',
      category: 'Shirts',
      image: '/images/Pant2.jpg',
      brand: 'Nike',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};

export default data;
